added a add comment function
krahma93/NC-News-FE pull request #7
Opened 2023-01-11 11:52 UTC by krahma93

2023-01-11 12:20 UTC, lewispricey requested changes
Great work on this one so far Khaled!

Overall very solid, really like that you're thinking about using semantic HTML tags rarther than divs to hold content.

I've left a few notes on the code but essentualy:
* Please could you add verification on the body so I can't post a blank comment
* Could you remove the user Input and hardcode a user in the new comment object instead - anyone trying out your app will find it difficut to know what user exists and doing it this way makes things easier to switch to using a login if you get that far :) 

Please send though another PR once these changes have been made.

2023-01-11 12:20 UTC, lewispricey commented on src/components/AddComment.jsx
> +    setComments((currComments) => {
Great use of optimistic rendering here 👍

2023-01-11 12:20 UTC, lewispricey commented on src/components/AddComment.jsx
> +    <input id="newBody"
Instead of input you may want to use text area here so this allows multi-line input

2023-01-11 12:20 UTC, lewispricey commented on src/components/AddComment.jsx
> +    e.preventDefault();
Please could you add in a validation check so I can't post a comment with a blank body

2023-01-11 12:20 UTC, lewispricey commented on src/components/AddComment.jsx
> +        username: newAuthor,
Rarther than a text input box for the username (difficult to know which users exist) please could you hardcode a username here and remove the username input. 

This way you can modify it to use a login much easier if you get there 👍 

*Same for the author key on this object

2023-01-11 12:20 UTC, lewispricey commented on src/components/Comments.jsx
> +        <section>
Great choice of semantic HTML tags here!

2023-01-11 12:20 UTC, lewispricey commented on src/components/AddComment.jsx
> +    setErr('Sorry your comment can not be added')
Nice use of error handling to make a user aware something went wrong

2023-01-12 10:40 UTC, RichardNeat requested changes
Hi Khaled, a few changes needed please. It's very difficult for me to see what you've been working on here as it's pieces of a couple of tickets on one pull request. Please make sure that a pr is relevant to only one ticket and the code included is only relevant to that one ticket as well.
I've made a couple of comments and it looks like Lewis has left some comments to which I can't see if they've been worked on?
Could you have a look, make sure all updates have been made and remove any code not relevant to the one ticket you are submitting the pr for?
Hope that makes sense, let me know if you want to have a chat :)

2023-01-12 10:40 UTC, RichardNeat commented on src/api.js
> +    if (slug) { return marketApi.get(`/articles?topic=${slug}`).then((res)=>
We could look at using the one api call and handling the options in the api.js file. We don't actually need to make two separate api calls here.

2023-01-12 10:40 UTC, RichardNeat commented on src/api.js
> +    console.log(article_id)
please remove any stray console logs

2023-01-12 10:40 UTC, RichardNeat commented on src/api.js
> +// export const getSingleTopic = (slug) => {
please remove any commented out code

2023-01-12 11:31 UTC, lewispricey approved these changes
Great work on these tickets Khaled!

Realy like that you've kept the code readable and modified your current functions so these can be re-used.

Please remove the commented code I've flagged then your good to merge 🚀

2023-01-12 11:31 UTC, lewispricey commented on src/api.js
> +    params: {topic: slug,}
Great use of Axios Params here to keep the code clean 👍

2023-01-12 11:31 UTC, lewispricey commented on src/components/AddComment.jsx
> +    if (!newBody)  {
This is a good validation check, stops the backend recieving a lot of blank comments from misclicks

2023-01-12 11:31 UTC, lewispricey commented on src/components/AddComment.jsx
> +    <input id="newAuthor"
Please could you remove this commented out section

2023-01-12 11:31 UTC, lewispricey commented on src/components/AddComment.jsx
> +    onChange={(e)=> setNewbody(e.target.value)}></textarea>
Like the use of state to control the input!

2023-01-12 11:31 UTC, lewispricey commented on src/components/AllArticles.jsx
> +        getArticles(slug).then((res)=> {
Great reuse of your current function, the code looks very neat and readable

2023-01-12 11:31 UTC, lewispricey commented on src/components/AllArticles.jsx
> +    const {slug} = useParams()
Param's is ideal here to get the category if it exists 💯

2023-01-12 11:50 UTC, merged